In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import mlfinlab as ml
from alpha_vantage.timeseries import TimeSeries

In [10]:
ts = TimeSeries(key = 'PTME3FLJAHB9CY', output_format = 'pandas')

In [11]:
data, meta_data = ts.get_daily_adjusted(symbol = 'MSFT', outputsize = 'full')

In [12]:
data

,1. open,2. high,3. low,4. close,5. adjusted close,6. volume,7. dividend amount,8. split coefficient
date,,,,,,,,
2020-01-16,164.3500,166.24,164.03,166.17,166.1700,22348621.0,0.0,1.0
2020-01-15,162.6200,163.94,162.57,163.18,163.1800,21417871.0,0.0,1.0
2020-01-14,163.3900,163.60,161.72,162.13,162.1300,23500783.0,0.0,1.0
2020-01-13,161.7600,163.31,161.26,163.28,163.2800,18666414.0,0.0,1.0
2020-01-10,162.8235,163.22,161.18,161.34,161.3400,20733946.0,0.0,1.0
...,...,...,...,...,...,...,...,...
2000-01-24,103.8000,105.69,100.81,101.25,32.6408,31798800.0,0.0,1.0
2000-01-21,107.0000,107.25,103.25,103.75,33.4468,34208100.0,0.0,1.0
2000-01-20,107.0600,109.69,105.87,106.00,34.1721,28174900.0,0.0,1.0
2000-01-19,110.5000,111.50,106.00,107.00,34.4945,48784100.0,0.0,1.0
2000-01-18,111.8100,116.50,111.75,115.31,37.1735,40741800.0,0.0,1.0

In [15]:
data.plot()
plt.show()

/Users/marcusahlgren/.local/share/virtualenvs/financial_ML-WJfqPqib/lib/python3.7/site-packages/ipykernel_launcher.py:2: UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.

In [14]:
import tkinter